name = "insight-hunter-demo"
pages_build_output_dir = "./dist"      # Vite build output
compatibility_date = "2024-11-12"      # keep in sync with your scripts
# compatibility_flags = ["nodejs_compat"]  # uncomment if you need Node built-ins

[vars]
APP_NAME = "Insight Hunter"
ENV = "production"

[env.preview]
# Overrides for preview deployments (optional)
[env.preview.vars]
ENV = "preview"

